# Copyright (C) 2014 Google Inc.
#
# This file is part of ycmd.
#
# ycmd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ycmd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ycmd.  If not, see <http://www.gnu.org/licenses/>.

import os
import ycm_core

#$BELLE2_RELEASE_DIR/include
# These are the compilation flags that will be used in case there's no
# compilation database set (by default, one is not set).
# CHANGE THIS LIST OF FLAGS. YES, THIS IS THE DROID YOU HAVE BEEN LOOKING FOR.
flags = [
    '-Wunused',
    '-Wuninitialized',
    '-Wno-long-long',
    '-Wno-variadic-macros',
    '-fexceptions',
    '-fno-builtin',
    '-DG4LIB_BUILD_DLL',
    '-DG4UI_USE_QT',
    '-DG4UI_USE_XM',
    '-DG4VIS_USE_OI',
    '-DG4VIS_USE_OIQT',
    '-DG4VIS_USE_OPENGLQT',
    '-DG4VIS_USE_OPENGLX',
    '-DG4VIS_USE_OPENGLXM',
    '-DG4VIS_USE_QT3D',
    '-DG4VIS_USE_RAYTRACERX',
    '-DG4VIS_USE_TOOLSSG_QT_GLES',
    '-DG4VIS_USE_TOOLSSG_QT_ZB',
    '-DG4VIS_USE_TOOLSSG_X11_GLES',
    '-DG4VIS_USE_TOOLSSG_X11_ZB',
    '-DG4VIS_USE_TOOLSSG_XT_GLES',
    '-DG4VIS_USE_TOOLSSG_XT_ZB',
    '-DG4VIS_USE_VTK',
    '-DG4VIS_USE_VTK_QT',
    '-DPTL_BUILD_DLL',
    '-DQT_CORE_LIB',
    '-DQT_GUI_LIB',
    '-DQT_NO_DEBUG',
    '-DQT_WIDGETS_LIB',
    # THIS IS IMPORTANT! Without a "-std=<something>" flag, clang won't know which
    # language to use when compiling headers. So it will guess. Badly. So C++
    # headers will be compiled as C headers. You don't want that so ALWAYS specify
    # a "-std=<something>".
    # For a C project, you would set this to something like 'c99' instead of
    # 'c++11'.
    '-std=c++20',
    '-fmodules',
    # ...and the same thing goes for the magic -x option which specifies the
    # language that the files to be compiled are written in. This is mostly
    # relevant for c++ headers.
    # This path will only work on OS X, but extra paths that don't exist are not
    # harmful
    #'-isystem', '/System/Library/Frameworks/Python.framework/Headers',

    # Place paths from the command
    #  $ echo | gcc -std=c++11 -v -E -x c++ -      when you use gcc
    #  $ echo | clang -std=c++11 -stdlib=libc++ -v -E -x c++ -     when you use clang
    #

    # For a C project, you would set this to 'c' instead of 'c++'.
    '-x',
    'c++',
    '-isystem', '/usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15',
    '-isystem', '/usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/x86_64-redhat-linux',
    '-isystem', '/usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/backward',
    '-isystem', '/usr/lib/gcc/x86_64-redhat-linux/15/include',
    '-isystem', '/usr/local/include',
    '-isystem', '/usr/include',

    '-isystem', '/storage/software/root/6.36.04/x86_64/fc42-gcc15.2.1/include',
    '-isystem', '/storage/software/Geant4/11.3.2/x86_64/fc42-gcc15.1.1/include/Geant4',
]

nowdir="@PROJECT_SOURCE_DIR@"

if nowdir[0]=='@':
    nowdir='.'

flags.append(f'-I{nowdir}/simobj/include')
flags.append(f'-I{nowdir}/simcore/include')
flags.append(f'-I{nowdir}/bl10sim/include')
flags.append(f'-I{nowdir}/kobetdsim/include')
flags.append(f'-I{nowdir}/include')


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags.
compilation_database_folder = ''

if os.path.exists(compilation_database_folder):
    database = ycm_core.CompilationDatabase(compilation_database_folder)
else:
    database = None

SOURCE_EXTENSIONS = ['.cpp', '.cxx', '.cc', '.c', '.m', '.mm']


def DirectoryOfThisScript():
    return os.path.dirname(os.path.abspath(__file__))


def IsHeaderFile(filename):
    extension = os.path.splitext(filename)[1]
    return extension in ['.h', '.hxx', '.hpp', '.hh']


def GetCompilationInfoForFile(filename):
    # The compilation_commands.json file generated by CMake does not have entries
    # for header files. So we do our best by asking the db for flags for a
    # corresponding source file, if any. If one exists, the flags for that file
    # should be good enough.
    if IsHeaderFile(filename):
        basename = os.path.splitext(filename)[0]
        for extension in SOURCE_EXTENSIONS:
            replacement_file = basename + extension
            if os.path.exists(replacement_file):
                compilation_info = database.GetCompilationInfoForFile(
                    replacement_file)
                if compilation_info.compiler_flags_:
                    return compilation_info
        return None
    return database.GetCompilationInfoForFile(filename)


# This is the entry point; this function is called by ycmd to produce flags for
# a file.
def Settings(**kwargs):
    if not database:
        return {
            'flags': flags,
            'include_paths_relative_to_dir': DirectoryOfThisScript()
        }
    filename = kwargs['filename']
    compilation_info = GetCompilationInfoForFile(filename)
    if not compilation_info:
        return None

    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object.
    return {
        'flags': list(compilation_info.compiler_flags_),
        'include_paths_relative_to_dir': compilation_info.compiler_working_dir_
    }

def PythonSysPath( **kwargs ):
  pythonEnv = os.getenv("PYTHONPATH")
  sys_path = kwargs[ 'sys_path' ]
  if pythonEnv == None:
      pass
  else:
      pypathList = pythonEnv.split(":");
      for i in pypathList:
          isExist = i in sys_path
          if isExist:
              print("EXIST")
          else:
              sys_path.insert(0, i)
  return sys_path
