#those commands must be come before /run/initialize comand

# number of threads
/run/numberOfThreads 25

# true: use Borated PE for the shielding blocks
/kobetdsim/det/useBPE true

# pe_blocks: original geometry with PE blocks
# hemisphere_det: a simple geometry only with hemisphere detector and primary source
# sphere_det: a simple geometry only with sphere detector and primary source
/kobetdsim/det/geom_type pe_blocks

# true: use realistic beampipe geometry
# false: use simplified geometry
/kobetdsim/det/beampipe true

# external_sequential: loads the vertex in the input file sequentially
#                      (if it reaches to the end, it will not generate events)
# external_neutron_sampling: samples the "neutron" vertex from the input file ramdomly.
# neutron: neutron generation mode on the target surface
# deuteron: deuteron generation mode in the ceramic cavity
/kobetdsim/primary/mode external_neutron_sampling

# the filename for the inputs for the primary vertex generation.
# this is required only in external_sequential and external_neutron_sampling
/kobetdsim/primary/filename primary.dat

/run/initialize

# name of the output file
/kobetdsim/ntuples/filename testO.root

/run/beamOn 1000000
